### ISSUE TITLE
Problem loading the Companies fixture

### ISSUE THREAD

**Issue by luanfonceca** [datasciencebr/jarbas#235]
I figure out that the problem was in the `Command`, there are some dict calls that uses the `['key']` notation instead of `.get('key')`. Which breaks if there are no keys with that name in the `row` dict.
Beyond that, in the `to_number` and `to_date` methods of `LoadCommand` class, they are not expecting `None` values in the parameters.

Follow a traceback for the companies fixture
```
python manage.py companies contrib/sample-data/companies_sample.xz
Starting with 0 companies
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/luan/Sources/env2jarbas/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/luan/Sources/env2jarbas/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/luan/Sources/env2jarbas/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/luan/Sources/env2jarbas/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/luan/Sources/jarbas/jarbas/core/management/commands/companies.py", line 24, in handle
    self.save_companies()
  File "/Users/luan/Sources/jarbas/jarbas/core/management/commands/companies.py", line 38, in save_companies
    obj = Company.objects.create(**self.serialize(filtered))
  File "/Users/luan/Sources/jarbas/jarbas/core/management/commands/companies.py", line 67, in serialize
    row['email'] = self.to_email(row['email'])
KeyError: 'email'
```

**Comment by cuducos** [comment]
> there are some dict calls that uses the `['key']` notation instead of `.get('key')`

This was intended. A row from the `csv.DictReader` should **always** have the expected _columns_ — otherwise we'll know something went wrong. Which I think is the case…

Recently we changed the `YYYY-MM-DD-companies.xz` adding columns for company partners and we might have missed the chance to update this script. I cannot check that ATM but the point is: the usa of `['key']` was not by accident ; )

**Comment by luanfonceca** [comment]
Hi @cuducos, I dont have any clue about what rosie should do, so i dig in into the command code. I would love to contribute with jarbas, cause is where i have more know how. But for do that i need to have a working dataset. If you or @jtemporal can send me a working version of a dataset i will be able to contribute more.

**Comment by cuducos** [comment]
Here we go, freshly brewed yesterday: the [reimbursements](https://www.dropbox.com/s/baror84orxaxt35/2017-08-10-reimbursements.xz?dl=0) and the [suspicious](https://www.dropbox.com/s/hhgig6mi2mcd9j2/2017-08-10-suspicions.xz?dl=0) ; )

---

_Disclaimer: gonna delete these files in a couple of days to free up some space…_

**Comment by cuducos** [comment]
About the companies dataset:

Just install `serenata-toolbox` and download `2017-05-21-companies-no-geolocation.xz` as described [in example 2](https://github.com/datasciencebr/serenata-toolbox#example-2-using-shortcuts) of its docs ; )

The older companies dataset is `2016-09-03-companies.xz` and can be dowloaded the same way.

**Comment by luanfonceca** [comment]
Hi @cuducos. I am getting the same error with the new dataset :(

```
$ bpython
bpython version 0.16 on top of Python 3.6.1 /Users/luan/Sources/env2jarbas/bin/python3
>>> from serenata_toolbox.datasets import fetch, fetch_latest_backup
>>>
>>> fetch('2017-05-21-companies-no-geolocation.xz', '../serenata-data/')

Downloading 2017-05-21-companies-no-geolocation.xz:   0%|                              | 0.00/7.49M [00:00<?, ?b/s
Downloading 2017-05-21-companies-no-geolocation.xz: 100%|######################| 7.49M/7.49M [00:12<00:00, 590Kb/s]
>>>

$ ./manage.py companies ../serenata-data/2017-05-21-companies-no-geolocation.xz
Starting with 56,900 companies
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/luan/Sources/env2jarbas/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/luan/Sources/env2jarbas/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/luan/Sources/env2jarbas/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/luan/Sources/env2jarbas/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/luan/Sources/jarbas/jarbas/core/management/commands/companies.py", line 24, in handle
    self.save_companies()
  File "/Users/luan/Sources/jarbas/jarbas/core/management/commands/companies.py", line 38, in save_companies
    obj = Company.objects.create(**self.serialize(filtered))
  File "/Users/luan/Sources/jarbas/jarbas/core/management/commands/companies.py", line 67, in serialize
    row['email'] = self.to_email(row['email'])
KeyError: 'email'
```

**Comment by cuducos** [comment]
> I am getting the same error with the new dataset :(

So maybe that's the case I described earlier:

> Recently we changed the `YYYY-MM-DD-companies.xz` adding columns for company partners and we might have missed the chance to update this script.

In other words: `2017-05-21-companies-no-geolocation.xz`  have a different columns than `016-09-03-companies.xz` and this Jarbas serializer needs to be updated : /
